//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatboxVido.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VidoEntities : DbContext
    {
        public VidoEntities()
            : base("name=VidoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<ApplicationConfig> ApplicationConfigs { get; set; }
        public virtual DbSet<CrispMessage> CrispMessages { get; set; }
        public virtual DbSet<FQA> FQAs { get; set; }
        public virtual DbSet<FQADetail> FQADetails { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Sender> Senders { get; set; }
    
        public virtual ObjectResult<usp_GetContactListForChatApplication_Result> usp_GetContactListForChatApplication()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetContactListForChatApplication_Result>("usp_GetContactListForChatApplication");
        }
    
        public virtual ObjectResult<usp_GetCrispMessagesForChatApplication_Result> usp_GetCrispMessagesForChatApplication(string contactID)
        {
            var contactIDParameter = contactID != null ?
                new ObjectParameter("ContactID", contactID) :
                new ObjectParameter("ContactID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetCrispMessagesForChatApplication_Result>("usp_GetCrispMessagesForChatApplication", contactIDParameter);
        }
    }
}
