//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatboxVido.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrispMessage
    {
        public int Id { get; set; }
        public string Website_Id { get; set; }
        public string Event { get; set; }
        public string Session_Id { get; set; }
        public string Type { get; set; }
        public string Content { get; set; }
        public string From { get; set; }
        public string Origin { get; set; }
        public long Timestamp { get; set; }
        public bool Stamped { get; set; }
        public long Fingerprint { get; set; }
        public string Nickname { get; set; }
        public string User_Id { get; set; }
        public string AppId { get; set; }
        public string SenderId { get; set; }
        public string RecipientId { get; set; }
        public string EventName { get; set; }
        public string MsgText { get; set; }
        public string MsgId { get; set; }
        public string ImageSource { get; set; }
        public bool FirstMessage { get; set; }

        public int src { get; set; }
        public long time { get; set; }
        public string type { get; set; }
        public string message { get; set; }
        public string message_id { get; set; }
        public string from_id { get; set; }
        public string to_id { get; set; }
        public string from_display_name { get; set; }
        public string from_avatar { get; set; }
        public string to_display_name { get; set; }
        public string to_avatar { get; set; }
    }
    //public class GetMessageHistory
    //{
    //    public List<CrispMessage> data { get; set; }
    //    public int error { get; set; }
    //    public string message { get; set; }
    //}
}
