//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatboxVido.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FQA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FQA()
        {
            this.FQADetails = new HashSet<FQADetail>();
        }
    
        public int Id { get; set; }
        public string Type { get; set; }
        public string Answers { get; set; }
        public Nullable<byte> STT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FQADetail> FQADetails { get; set; }
    }
}
