//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatboxVido.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FQADetail
    {
        public int Id { get; set; }
        public int FQAId { get; set; }
        public string Question { get; set; }
        public Nullable<int> QuestionType { get; set; }
    
        public virtual FQA FQA { get; set; }
    }
}
