//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatboxVido.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public string AppId { get; set; }
        public string SenderId { get; set; }
        public string RecipientId { get; set; }
        public string EventName { get; set; }
        public string MsgText { get; set; }
        public string MsgId { get; set; }
        public string Timestamp { get; set; }
    
        public virtual Sender Sender { get; set; }
    }
}
